### ISSUE TITLE
Request for Changelog and Compatibility with tsdl.1.0.0

### ISSUE THREAD

**Issue by mbarbin** [sanette/bogue#20]
Hello,

I've had a positive experience using bogue for a small application[^1] in a past
student project of mine. I appreciate your work on bogue!

I noticed the recent release of `bogue.20231209` on opam. Currently, I'm using
`bogue.20221112` and I'm considering an upgrade. However, I couldn't find a
changelog for this project. Would it be possible to include one in the root of
the GitHub project?

Additionally, I observed that the latest version of `tsdl` is `1.0.0`, but bogue
still requires `tsdl >= 0.9.7 & <0.9.9`. Are there any obstacles preventing the
support for `tsdl.1.0.0` in the future?

Please note that this is a low-priority request and it's not blocking me in any
way. I'm not currently working on a project that depends on `bogue` or `tsdl`.
I'm simply trying to stay up to date with the latest versions.

Thank you for your time!

[^1]: [visa-deboguer](https://mbarbin.github.io/bopkit/project/visa/doc/assembler/#debugger)

**Comment by sanette** [comment]
Hi thanks for your message!

1. concerning changelog, you are of course right, I should have such a file... For the moment you have to browse the git history to see the changes, but it's not always easy.  Concerning the latest release, the main change was to better detect the user config directories, in particular for the Windows OS.
2. concerning tsdl, it's a difficult issue because tsdl 1.0.0 is not compatible with earlier versions, and some linux systems have by default old SDL libraries that are not compatible with tsdl 1.0.0... However these systems are getting old by now, and I do consider requiring newer SDL and switching to tsdl 1.0.0 in the near future!

**Comment by mbarbin** [comment]
Hi @sanette . Thank you for your response!

Thank you for letting me know about the latest release main change.

Sounds like things are on your radar, so I will be closing this issue. Good luck with the switch to tsdl 1.0.0 in the future!
