### ISSUE TITLE
Mouse.pointer_pos x,y cordinates not giving exact positions

### ISSUE THREAD

**Issue by IdaraNabuk** [sanette/bogue#30]
I'm working on the circle drawer in Bogue and I'm having issues with getting the mouse to draw at an exact coordinates point. The circles are drawn at a distance away from the mouse point.

Here's a screenshot of the error as the mouse is drawing the circle from where it is located.
![Circledrawer Issue](https://github.com/sanette/bogue/assets/44207022/d8667bf1-ea15-4e0d-ace9-2d4b1bc779ca)

[Here's the link to the repo](https://github.com/IdaraNabuk/Bogue-examples/tree/main/bogue_circledrawer)

**Comment by sanette** [comment]
Hi, short answer: use `Sdl_area.pointer_pos` instead of `Mouse.pointer_pos`.

Why? well there are some subtleties about Bogue coordinates that you need to know: because Bogue is designed to work with Hi-DPI screens, there are two (or in fact, three for MacOS retina, but let's forget about this) types of pixels: hardware pixels corresponding to your screen resolution, and Bogue logical pixels, so that a box of (logical) size 400x400 look roughly the same on all monitors.

Now we come to your problem:
* `Mouse.pointer_pos` returns *logical* coordinates (this is indicated in `Mouse` documentation)
* But `Sdl_area`s work with hardware coordinates (why? because the idea is to let the user makes best use of her hardware when drawing)

So you have several solutions:
* either convert using `Sdl_area.to_pixels`
* (better: more precise) use `Sdl_area.pointer_pos`
* (not recommended) use directly SDL functions. 
 
There is a Bogue demo that you may like that uses `Sdl_area.pointer_pos`:
https://github.com/sanette/drawing-demo/blob/master/drawing.ml

In fact, in this demo, a previous version used directly SDL functions:
https://github.com/sanette/drawing-demo/blob/f1865412db8291026131e1b9a2d61abc4ab6e33b/drawing.ml#L49C1-L55C32
But this function is not used anymore (forgot to remove it ;-) ) because some SDL versions didn't take into account Mac OS retina scaling)

**Comment by sanette** [comment]
Oh, in fact there is another difference which probably is the real cause of your problem: `Mouse.pointer_pos` gives the position with respect to the top-left corner of the *window*, while `Sdl_area.pointer_pos` gives the position with respect to the top-left corner of the *Sdl_area widget* (which is most probably what you want)

**Comment by IdaraNabuk** [comment]
Thank you so much. This was helpful. The circles are drawing perfectly well now.
