### ISSUE TITLE
Allowing buttons to be disabled

### ISSUE THREAD

**Issue by msub2** [sanette/bogue#38]
Hello! Thank you for working on this library, it's been great as I've been starting to learn OCaml. I'm wondering whether it's possible to set a button as disabled, or whether there'd need to be some kind of feature addition to help better facilitate that. Here's a screenshot of what I'm working on for reference

![image](https://github.com/user-attachments/assets/35878115-23a5-4d4b-ac6b-d137af434adb)

The idea would be that when you reach the beginning of your history, the back button would be disabled until moving forward, and vice versa for the forward button. I can add some logic to prevent navigation in these cases but I wasn't sure how to approach the change visually.

**Comment by sanette** [comment]
Hi,, thanks for the feedback; yes it would be a very natural extension to add (and probably not difficult to implement)
Current this can be achieved using a hiding pop-up like `boguex 21` example: the pop up hides the select button, so that you cannot click on it. But it would be a lot of code for just a button...

**Comment by sanette** [comment]
In fact there is something much easier: you could simply `hide` the layout containing the button, see
http://sanette.github.io/bogue/Bogue.Layout.html#VALhide

**Comment by sanette** [comment]
I just added a new feature, see example `boguex 53bis`
